package repositories

import (
 "context"; "database/sql"; "errors"; "fmt"; "time"
 "workstream-backend/internal/database"; "workstream-backend/internal/models"
)
var ( ErrPaymentNotFound = errors.New("payment not found"); ErrPaymentConflict = errors.New("payment state conflict"); ErrWalletNotFound = errors.New("wallet not found") )
type PaymentRepository interface { FundTx(context.Context,*models.Payment) error; ReleaseTx(context.Context,string,time.Time) error; RefundTx(context.Context,string,time.Time) error; GetByID(context.Context,string)(*models.Payment,error); GetByMilestoneID(context.Context,string)(*models.Payment,error); GetByContractID(context.Context,string)([]models.Payment,error); GetByUserID(context.Context,string)([]models.Payment,error); GetWallet(context.Context,string)(*models.Wallet,error); GetLedger(context.Context,string)([]models.LedgerEntry,error) }
type paymentRepository struct{ db *database.DBWrapper }
func NewPaymentRepository(db *database.DBWrapper) PaymentRepository { return &paymentRepository{db} }
func (r *paymentRepository) valid() error { if r.db==nil || r.db.DB==nil{return ErrDatabaseUnavailable}; return nil }
func scanPayment(row interface{Scan(...interface{}) error})(*models.Payment,error){ var p models.Payment; err:=row.Scan(&p.ID,&p.PaymentReference,&p.ContractID,&p.MilestoneID,&p.BuyerID,&p.FreelancerID,&p.AmountMinor,&p.PlatformFeeMinor,&p.FreelancerAmountMinor,&p.Currency,&p.Status,&p.Provider,&p.CreatedAt,&p.FundedAt,&p.ReleasedAt,&p.RefundedAt); if errors.Is(err,sql.ErrNoRows){return nil,ErrPaymentNotFound}; if err!=nil{return nil,err};return &p,nil }
const paymentSelect=`SELECT id,payment_reference,contract_id,milestone_id,buyer_id,freelancer_id,amount_minor,platform_fee_minor,freelancer_amount_minor,currency,status,provider,created_at,funded_at,released_at,refunded_at FROM payments`
func (r *paymentRepository) GetByID(c context.Context,id string)(*models.Payment,error){if e:=r.valid();e!=nil{return nil,e}; return scanPayment(r.db.QueryRowContext(c,paymentSelect+` WHERE id=$1`,id))}
func (r *paymentRepository) GetByMilestoneID(c context.Context,id string)(*models.Payment,error){if e:=r.valid();e!=nil{return nil,e}; return scanPayment(r.db.QueryRowContext(c,paymentSelect+` WHERE milestone_id=$1`,id))}
func (r *paymentRepository) list(c context.Context,q string,args ...interface{})([]models.Payment,error){ if e:=r.valid();e!=nil{return nil,e}; rows,e:=r.db.QueryContext(c,q,args...);if e!=nil{return nil,e};defer rows.Close(); var out []models.Payment;for rows.Next(){p,e:=scanPayment(rows);if e!=nil{return nil,e};out=append(out,*p)};return out,rows.Err() }
func (r *paymentRepository) GetByContractID(c context.Context,id string)([]models.Payment,error){return r.list(c,paymentSelect+` WHERE contract_id=$1 ORDER BY created_at DESC`,id)}
func (r *paymentRepository) GetByUserID(c context.Context,id string)([]models.Payment,error){return r.list(c,paymentSelect+` WHERE buyer_id=$1 OR freelancer_id=$1 ORDER BY created_at DESC`,id)}
func (r *paymentRepository) FundTx(c context.Context,p *models.Payment) error { if e:=r.valid();e!=nil{return e}; tx,e:=r.db.BeginTx(c,nil);if e!=nil{return e};defer tx.Rollback(); now:=time.Now().UTC(); _,e=tx.ExecContext(c,`INSERT INTO payments (id,payment_reference,contract_id,milestone_id,buyer_id,freelancer_id,amount_minor,platform_fee_minor,freelancer_amount_minor,currency,status,provider,created_at,funded_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'held','internal',$11,$11)`,p.ID,p.PaymentReference,p.ContractID,p.MilestoneID,p.BuyerID,p.FreelancerID,p.AmountMinor,p.PlatformFeeMinor,p.FreelancerAmountMinor,p.Currency,now);if e!=nil{return fmt.Errorf("create payment: %w",e)}; _,e=tx.ExecContext(c,`INSERT INTO wallets(id,user_id,pending_balance_minor,currency) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET pending_balance_minor=wallets.pending_balance_minor+EXCLUDED.pending_balance_minor,updated_at=NOW()`,"wal_"+p.FreelancerID,p.FreelancerID,p.FreelancerAmountMinor,p.Currency);if e!=nil{return e};_,e=tx.ExecContext(c,`INSERT INTO ledger_entries(id,transaction_reference,user_id,payment_id,contract_id,milestone_id,entry_type,amount_minor,currency,description) VALUES($1,$2,$3,$4,$5,$6,'milestone_funded',$7,$8,$9)`,"led_"+p.ID,"fund:"+p.ID,p.BuyerID,p.ID,p.ContractID,p.MilestoneID,p.AmountMinor,p.Currency,"Milestone funded and held in internal escrow");if e!=nil{return e}; return tx.Commit() }
func (r *paymentRepository) ReleaseTx(c context.Context,id string,now time.Time) error {if e:=r.valid();e!=nil{return e};tx,e:=r.db.BeginTx(c,nil);if e!=nil{return e};defer tx.Rollback();p,e:=scanPayment(tx.QueryRowContext(c,paymentSelect+` WHERE id=$1 FOR UPDATE`,id));if e!=nil{return e};if p.Status!=models.PaymentStatusHeld{return ErrPaymentConflict};var approved bool;e=tx.QueryRowContext(c,`SELECT status='approved' FROM milestones WHERE id=$1`,p.MilestoneID).Scan(&approved);if e!=nil||!approved{return ErrPaymentConflict};res,e:=tx.ExecContext(c,`UPDATE payments SET status='released',released_at=$1 WHERE id=$2 AND status='held'`,now,id);if e!=nil{return e};n,_:=res.RowsAffected();if n!=1{return ErrPaymentConflict};_,e=tx.ExecContext(c,`UPDATE wallets SET pending_balance_minor=pending_balance_minor-$1,available_balance_minor=available_balance_minor+$1,total_earned_minor=total_earned_minor+$1,updated_at=$2 WHERE user_id=$3 AND pending_balance_minor >= $1`,p.FreelancerAmountMinor,now,p.FreelancerID);if e!=nil{return e}; _,e=tx.ExecContext(c,`INSERT INTO ledger_entries(id,transaction_reference,user_id,payment_id,contract_id,milestone_id,entry_type,amount_minor,currency,description) VALUES($1,$2,$3,$4,$5,$6,'freelancer_earning',$7,$8,$9),($10,$11,NULL,$4,$5,$6,'platform_fee',$12,$8,$13),($14,$15,$3,$4,$5,$6,'milestone_release',$7,$8,$16)`,"led_earn_"+id,"earn:"+id,p.FreelancerID,id,p.ContractID,p.MilestoneID,p.FreelancerAmountMinor,p.Currency,"Freelancer earning released", "led_fee_"+id,"fee:"+id,p.PlatformFeeMinor,"Platform fee recorded", "led_release_"+id,"release:"+id,"Milestone escrow released");if e!=nil{return e};return tx.Commit() }
func (r *paymentRepository) RefundTx(c context.Context,id string,now time.Time) error {if e:=r.valid();e!=nil{return e};tx,e:=r.db.BeginTx(c,nil);if e!=nil{return e};defer tx.Rollback();p,e:=scanPayment(tx.QueryRowContext(c,paymentSelect+` WHERE id=$1 FOR UPDATE`,id));if e!=nil{return e};if p.Status!=models.PaymentStatusHeld{return ErrPaymentConflict};_,e=tx.ExecContext(c,`UPDATE payments SET status='refunded',refunded_at=$1 WHERE id=$2 AND status='held'`,now,id);if e!=nil{return e};_,e=tx.ExecContext(c,`UPDATE wallets SET pending_balance_minor=pending_balance_minor-$1,updated_at=$2 WHERE user_id=$3 AND pending_balance_minor >= $1`,p.FreelancerAmountMinor,now,p.FreelancerID);if e!=nil{return e};_,e=tx.ExecContext(c,`INSERT INTO ledger_entries(id,transaction_reference,user_id,payment_id,contract_id,milestone_id,entry_type,amount_minor,currency,description) VALUES($1,$2,$3,$4,$5,$6,'refund',$7,$8,$9)`,"led_refund_"+id,"refund:"+id,p.BuyerID,id,p.ContractID,p.MilestoneID,p.AmountMinor,p.Currency,"Internal escrow refund");if e!=nil{return e};return tx.Commit() }
func(r *paymentRepository) GetWallet(c context.Context,u string)(*models.Wallet,error){if e:=r.valid();e!=nil{return nil,e}; var w models.Wallet;e:=r.db.QueryRowContext(c,`SELECT id,user_id,available_balance_minor,pending_balance_minor,total_earned_minor,total_withdrawn_minor,currency,updated_at FROM wallets WHERE user_id=$1`,u).Scan(&w.ID,&w.UserID,&w.AvailableBalanceMinor,&w.PendingBalanceMinor,&w.TotalEarnedMinor,&w.TotalWithdrawnMinor,&w.Currency,&w.UpdatedAt);if errors.Is(e,sql.ErrNoRows){return nil,ErrWalletNotFound};return &w,e}
func(r *paymentRepository) GetLedger(c context.Context,u string)([]models.LedgerEntry,error){if e:=r.valid();e!=nil{return nil,e};rows,e:=r.db.QueryContext(c,`SELECT id,transaction_reference,user_id,payment_id,contract_id,milestone_id,entry_type,amount_minor,currency,description,created_at FROM ledger_entries WHERE user_id=$1 ORDER BY created_at DESC`,u);if e!=nil{return nil,e};defer rows.Close();var out []models.LedgerEntry;for rows.Next(){var x models.LedgerEntry;if e=rows.Scan(&x.ID,&x.TransactionReference,&x.UserID,&x.PaymentID,&x.ContractID,&x.MilestoneID,&x.EntryType,&x.AmountMinor,&x.Currency,&x.Description,&x.CreatedAt);e!=nil{return nil,e};out=append(out,x)};return out,rows.Err()}
