package services
import("context";"errors";"fmt";"math";"strings";"sync/atomic";"time";"workstream-backend/internal/models";"workstream-backend/internal/repositories")
var paymentCounter uint64
type PaymentService interface { FundMilestone(context.Context,string,string,string)(*models.Payment,error); ReleasePayment(context.Context,string,string,string)error; RefundPayment(context.Context,string,string,string)error; GetPayment(context.Context,string,string,string)(*models.Payment,error); GetMilestonePayment(context.Context,string,string,string)(*models.Payment,error); GetContractPayments(context.Context,string,string,string)([]models.Payment,error); GetMyPayments(context.Context,string)([]models.Payment,error); GetWallet(context.Context,string)(*models.Wallet,error); GetLedger(context.Context,string)([]models.LedgerEntry,error) }
type paymentService struct { payments repositories.PaymentRepository; milestones repositories.MilestoneRepository; contracts repositories.ContractRepository }
func NewPaymentService(p repositories.PaymentRepository,m repositories.MilestoneRepository,c repositories.ContractRepository) PaymentService{return &paymentService{p,m,c}}
func isAdmin(role string)bool{return strings.EqualFold(role,"admin")}
func (s *paymentService) authorizePayment(c context.Context,p *models.Payment,u,role string)error{if isAdmin(role)||p.BuyerID==u||p.FreelancerID==u{return nil};return ErrForbidden}
func (s *paymentService) FundMilestone(c context.Context,milestoneID,userID,role string)(*models.Payment,error){m,e:=s.milestones.GetByID(c,milestoneID);if e!=nil{return nil,e};con,e:=s.contracts.GetByID(c,m.ContractID);if e!=nil{return nil,e};if !isAdmin(role)&&con.BuyerID!=userID{return nil,ErrForbidden};if m.Status!=models.MilestoneStatusPending{return nil,fmt.Errorf("%w: milestone must be pending before funding",ErrInvalidMilestoneState)};if _,e=s.payments.GetByMilestoneID(c,milestoneID);e==nil{return nil,repositories.ErrPaymentConflict}else if !errors.Is(e,repositories.ErrPaymentNotFound){return nil,e};amount:=int64(math.Round(m.Amount*100));if amount<=0{return nil,errors.New("milestone amount must be greater than zero")};fee:=amount*models.PlatformFeePercent/100; p:=&models.Payment{ID:fmt.Sprintf("pay_%d_%d",time.Now().UnixMilli(),atomic.AddUint64(&paymentCounter,1)),PaymentReference:fmt.Sprintf("PAY-%d-%06d",time.Now().UTC().Year(),atomic.AddUint64(&paymentCounter,1)),ContractID:con.ID,MilestoneID:m.ID,BuyerID:con.BuyerID,FreelancerID:con.FreelancerID,AmountMinor:amount,PlatformFeeMinor:fee,FreelancerAmountMinor:amount-fee,Currency:"INR",Status:models.PaymentStatusHeld,Provider:"internal"};if e=s.payments.FundTx(c,p);e!=nil{return nil,e};return s.payments.GetByID(c,p.ID)}
func(s *paymentService) GetPayment(c context.Context,id,u,r string)(*models.Payment,error){p,e:=s.payments.GetByID(c,id);if e!=nil{return nil,e};return p,s.authorizePayment(c,p,u,r)}
func(s *paymentService) GetMilestonePayment(c context.Context,id,u,r string)(*models.Payment,error){p,e:=s.payments.GetByMilestoneID(c,id);if e!=nil{return nil,e};return p,s.authorizePayment(c,p,u,r)}
func(s *paymentService) GetContractPayments(c context.Context,id,u,r string)([]models.Payment,error){con,e:=s.contracts.GetByID(c,id);if e!=nil{return nil,e};if !isAdmin(r)&&con.BuyerID!=u&&con.FreelancerID!=u{return nil,ErrForbidden};return s.payments.GetByContractID(c,id)}
func(s *paymentService) GetMyPayments(c context.Context,u string)([]models.Payment,error){return s.payments.GetByUserID(c,u)}
func(s *paymentService) ReleasePayment(c context.Context,id,u,r string)error{p,e:=s.payments.GetByID(c,id);if e!=nil{return e};if !isAdmin(r)&&p.BuyerID!=u{return ErrForbidden};if p.Status!=models.PaymentStatusHeld{return repositories.ErrPaymentConflict};m,e:=s.milestones.GetByID(c,p.MilestoneID);if e!=nil{return e};if m.Status!=models.MilestoneStatusApproved{return fmt.Errorf("%w: milestone must be approved",ErrInvalidMilestoneState)};return s.payments.ReleaseTx(c,id,time.Now().UTC())}
func(s *paymentService) RefundPayment(c context.Context,id,u,r string)error{p,e:=s.payments.GetByID(c,id);if e!=nil{return e};if !isAdmin(r)&&p.BuyerID!=u{return ErrForbidden};if p.Status!=models.PaymentStatusHeld{return repositories.ErrPaymentConflict};return s.payments.RefundTx(c,id,time.Now().UTC())}
func(s *paymentService) GetWallet(c context.Context,u string)(*models.Wallet,error){w,e:=s.payments.GetWallet(c,u);if errors.Is(e,repositories.ErrWalletNotFound){return &models.Wallet{UserID:u,Currency:"INR"},nil};return w,e}
func(s *paymentService) GetLedger(c context.Context,u string)([]models.LedgerEntry,error){return s.payments.GetLedger(c,u)}
