import React, { useEffect, useState } from 'react';
import { Send, Sparkles } from 'lucide-react';
import { communicationApi } from '../../services/api/communicationApi';
import { rightSpeechService } from '../../services/rightSpeechService';

export default function Messages() {
  const [conversations, setConversations] = useState([]), [selected, setSelected] = useState(null), [messages, setMessages] = useState([]), [draft, setDraft] = useState(''), [suggestion, setSuggestion] = useState(null), [error, setError] = useState('');
  useEffect(() => { communicationApi.conversations().then(d => { const list=d.conversations||[]; setConversations(list); setSelected(list[0]||null); }).catch(e=>setError(e.message)); }, []);
  useEffect(() => { if (!selected) return; let live=true; const load=()=>communicationApi.messages(selected.id).then(d=>live&&setMessages((d.messages||[]).slice().reverse())).catch(e=>live&&setError(e.message)); load(); const timer=setInterval(load,5000); communicationApi.markMessagesRead(selected.id).catch(()=>{}); return()=>{live=false;clearInterval(timer)}; }, [selected?.id]);
  const send=async(e)=>{e.preventDefault(); if(!draft.trim()||!selected)return; try { await communicationApi.sendMessage(selected.id,draft); setDraft(''); setSuggestion(null); const d=await communicationApi.messages(selected.id);setMessages((d.messages||[]).slice().reverse()); }catch(err){setError(err.message)} };
  const consider=async(value)=>setSuggestion(await rightSpeechService.suggestImprovement(value));
  return <main className="container" style={{padding:'42px 0',minHeight:'65vh'}}><h1>Messages</h1>{error&&<p style={{color:'#ef4444'}}>{error}</p>}<div style={{display:'grid',gridTemplateColumns:'minmax(220px, .8fr) minmax(0, 2fr)',border:'1px solid var(--color-border)',borderRadius:14,overflow:'hidden',minHeight:460}}><aside style={{borderRight:'1px solid var(--color-border)',padding:12}}>{conversations.length===0?<p>No project conversations yet.</p>:conversations.map(c=><button key={c.id} onClick={()=>setSelected(c)} style={{display:'block',width:'100%',textAlign:'left',padding:12,border:0,borderRadius:8,background:selected?.id===c.id?'var(--color-surface)':'transparent',color:'inherit'}}><strong>Project conversation</strong><small style={{display:'block',opacity:.65}}>{c.unreadCount?`${c.unreadCount} unread`:'Up to date'}</small></button>)}</aside><section style={{display:'flex',flexDirection:'column',padding:18}}>{selected?<><div style={{flex:1}}>{messages.map(m=><div key={m.id} style={{margin:'10px 0',padding:10,borderRadius:10,background:'var(--color-surface)'}}>{m.message}<small style={{display:'block',opacity:.6}}>{new Date(m.createdAt).toLocaleString()}</small></div>)}</div>{suggestion&&<div style={{padding:10,marginBottom:8,borderRadius:8,background:'rgba(34,197,94,.12)'}}><Sparkles size={14}/> {suggestion.suggestion} <button onClick={()=>{setDraft(suggestion.suggestion);setSuggestion(null)}}>Use</button> <button onClick={()=>setSuggestion(null)}>Dismiss</button></div>}<form onSubmit={send} style={{display:'flex',gap:8}}><input value={draft} onChange={e=>{setDraft(e.target.value);consider(e.target.value)}} placeholder="Type a message…" style={{flex:1}}/><button className="btn btn-primary"><Send size={16}/> Send</button></form></>:<p>Select a conversation.</p>}</section></div></main>;
}
